    /* zlib functions */
    {"crc32", crc32},
    {"deflate", deflate},
    {"deflateEnd", deflateEnd},
    {"deflateInit2_", deflateInit2_},
    {"deflateReset", deflateReset},
    {"inflate", inflate},
    {"inflateEnd", inflateEnd},
    {"inflateInit2_", inflateInit2_},
    {"inflateInit_", inflateInit_},
    {"inflateReset", inflateReset},
    {"adler32", adler32},
    {"compress", compress},
    {"compress2", compress2},
    {"uncompress", uncompress},
